language: python
python:
  - 2.7
  - 3.6
  - 3.7
  - 3.8
sudo: false
cache:
  directories:
  - eggs
  - parts/node
jobs:
  exclude:
    - python: 3.6
      env: PLONE_VERSION=4.3
    - python: 3.6
      env: PLONE_VERSION=5.0
    - python: 3.6
      env: PLONE_VERSION=5.1
    - python: 3.7
      env: PLONE_VERSION=4.3
    - python: 3.7
      env: PLONE_VERSION=5.0
    - python: 3.7
      env: PLONE_VERSION=5.1
    - python: 3.8
      env: PLONE_VERSION=4.3
    - python: 3.8
      env: PLONE_VERSION=5.0
    - python: 3.8
      env: PLONE_VERSION=5.1
  fast_finish: true
env:
- PLONE_VERSION=4.3
- PLONE_VERSION=5.0
- PLONE_VERSION=5.1
- PLONE_VERSION=5.2
before_script:
- memcached -h
install:
- sed -ie "s#test-5.2#test-$PLONE_VERSION#" buildout.cfg
- pip install -r requirements.txt
- buildout annotate
- buildout
script:
- bin/code-analysis
- bin/test
after_success:
- bin/createcoverage --output-dir=htmlcov
- pip install coveralls
- coveralls
notifications:
  irc: irc.freenode.org#plone-testing
